<a href="https://colab.research.google.com/github/lilmiztee04/Uow_Data_Engineering/blob/main/ContentEfficencymodeldata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#load file and rename and checkk attributes
import pandas as pd
SME = pd.read_csv('/content/social_media_engagement1.csv')
display(SME.head())

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score
0,1,Facebook,image,8/17/2023 14:45,2121,474,628,Thursday,positive
1,2,Facebook,carousel,5/14/2023 0:45,3660,432,694,Sunday,neutral
2,3,Instagram,poll,2/21/2023 16:15,4955,408,688,Tuesday,negative
3,4,Twitter,image,11/16/2023 0:45,1183,90,187,Thursday,negative
4,5,Twitter,video,5/23/2023 0:30,3499,247,286,Tuesday,positive

In [2]:
#check if there are missing data and if dataset needs to be cleaned up
SME.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   post_id          100 non-null    int64
 1   platform         100 non-null    object
 2   post_type        100 non-null    object
 3   post_time        100 non-null    object
 4   likes            100 non-null    int64
 5   comments         100 non-null    int64
 6   shares           100 non-null    int64
 7   post_day         100 non-null    object
 8   sentiment_score  100 non-null    object
dtypes: int64(4), object(5)
memory usage: 7.2+ KB

In [3]:
#remove unnecessary attributes, twitter isnt needed as im focusing on meta platform
SME = SME[SME['platform'] != 'Twitter']
display(SME.head())

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score
0,1,Facebook,image,8/17/2023 14:45,2121,474,628,Thursday,positive
1,2,Facebook,carousel,5/14/2023 0:45,3660,432,694,Sunday,neutral
2,3,Instagram,poll,2/21/2023 16:15,4955,408,688,Tuesday,negative
5,6,Instagram,carousel,5/5/2023 20:00,256,186,211,Friday,neutral
6,7,Instagram,image,2/26/2023 11:45,1982,30,906,Sunday,positive

In [6]:
#create a new table for futher analytic analysis on when iis the best time to post advertisement
engagement_metrics = SME[['post_day','platform', 'post_time', 'likes', 'comments', 'shares']].copy()
display(engagement_metrics.head())

   post_day   platform        post_time  likes  comments  shares
0  Thursday   Facebook  8/17/2023 14:45   2121       474     628
1    Sunday   Facebook   5/14/2023 0:45   3660       432     694
2   Tuesday  Instagram  2/21/2023 16:15   4955       408     688
5    Friday  Instagram   5/5/2023 20:00    256       186     211
6    Sunday  Instagram  2/26/2023 11:45   1982        30     906

In [8]:
#new tabel created
postAna = engagement_metrics
display(postAna.head())

   post_day   platform        post_time  likes  comments  shares
0  Thursday   Facebook  8/17/2023 14:45   2121       474     628
1    Sunday   Facebook   5/14/2023 0:45   3660       432     694
2   Tuesday  Instagram  2/21/2023 16:15   4955       408     688
5    Friday  Instagram   5/5/2023 20:00    256       186     211
6    Sunday  Instagram  2/26/2023 11:45   1982        30     906

In [9]:
postAna.info()

<class 'pandas.core.frame.DataFrame'>
Index: 68 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   post_day   68 non-null     object
 1   platform   68 non-null     object
 2   post_time  68 non-null     object
 3   likes      68 non-null     int64
 4   comments   68 non-null     int64
 5   shares     68 non-null     int64
dtypes: int64(3), object(3)
memory usage: 3.7+ KB

In [13]:
# Save postAna DataFrame to a CSV file
postAna.to_csv('postAna.csv', index=False)
print('postAna.csv has been saved.')

postAna.csv has been saved.

In [14]:
import random

# Define a list of content themes based on user's input
content_themes = [
    'Informational/Educational',
    'Promotional (Product Specific)',
    'UGC (User Generated Content)',
    'Lifestyle/Brand Storytelling',
    'Trend-based'
]

# Randomly assign a content theme to each row in the SME DataFrame
SME['content_theme'] = [random.choice(content_themes) for _ in range(len(SME))]

# Display the head of the DataFrame with the new 'content_theme' column
display(SME.head())

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score,content_theme
0,1,Facebook,image,8/17/2023 14:45,2121,474,628,Thursday,positive,Promotional (Product Specific)
1,2,Facebook,carousel,5/14/2023 0:45,3660,432,694,Sunday,neutral,Promotional (Product Specific)
2,3,Instagram,poll,2/21/2023 16:15,4955,408,688,Tuesday,negative,Informational/Educational
5,6,Instagram,carousel,5/5/2023 20:00,256,186,211,Friday,neutral,Lifestyle/Brand Storytelling
6,7,Instagram,image,2/26/2023 11:45,1982,30,906,Sunday,positive,UGC (User Generated Content)

In [15]:
# Save SME DataFrame to a CSV file
SME.to_csv('SME.csv', index=False)
print('SME.csv has been saved.')

SME.csv has been saved.